version: '2'
services:
    jhbeard-app:
        image: jhbeard
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhbeard-mysql:3306/jhbeard?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    jhbeard-mysql:
        extends:
            file: mysql.yml
            service: jhbeard-mysql
